FROM oven/bun:latest as build
WORKDIR /manthan-client
COPY package.json .
RUN bun init
RUN bun install
COPY . .
RUN bun run build

FROM nginx:stable-alpine
COPY --from=build /manthan-client/out /usr/share/nginx/html
COPY --from=build /manthan-client/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# COPY --from=build /formjs/nginx/upstream.conf /etc/nginx/conf.d/loadbalancer.conf
# COPY --from=build /formjs/nginx/web.conf /etc/nginx/conf.d/web.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]