# --- Stage 1: Build ---
FROM oven/bun:1.3.1 AS build

WORKDIR /manthan-client

COPY bun.lock package.json ./

RUN bun install 

COPY . .

RUN bun run build


FROM nginx:stable-alpine

COPY --from=build /manthan-client/out /usr/share/nginx/html

COPY --from=build /manthan-client/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
