services:
  nginx-react:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    restart: always
    tty: true
    volumes:
      - ..:/manthan-client
      - ../nginx/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
