 server {
     listen 80;
     server_name manthan.kiet.edu;
     return 301 https://$host$request_uri;
 }
 
 upstream backend {
   server 192.168.1.14:8001;
 }

 server {
     listen 443 ssl;
     listen [::]:443 ssl;
     server_name manthan.kiet.edu;
     ssl_certificate /etc/ssl/kiet/kiet_11_07.pem;
     ssl_certificate_key /etc/ssl/kiet/kiet.key;

     location / {
        root /usr/share/nginx/html/;
        index index.html;
        try_files $uri /index.html;
     }
     
    #  location /api/media/ {
    #     rewrite /api/media/kiet_student/(.*) /upload_images/StudentMusterroll/Student_images/$1 break;
    #     proxy_pass https://tech.kiet.edu/;
    #     proxy_set_header Host tech.kiet.edu;
    #  }

     location /api/ {
        proxy_pass  http://backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

     }

    
 }
