# Redirect all HTTP to HTTPS
server {
    listen 80;
    server_name manthan.kiet.edu;
    return 301 https://$host$request_uri;
}

# upstream backend {
#     server 192.168.1.14:8000;
# }

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name manthan.kiet.edu;

    ssl_certificate /etc/ssl/kiet/kiet_11_07.pem;
    ssl_certificate_key /etc/ssl/kiet/kiet.key;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;



    root /usr/share/nginx/html/manthan-client/out;
    index index.html;

    location / {
        try_files $uri /index.html;
    }


    # location /api/media/ {
    #     rewrite /api/media/kiet_student/(.*) /upload_images/StudentMusterroll/Student_images/$1 break;
    #     proxy_pass https://tech.kiet.edu/;
    #     proxy_set_header Host tech.kiet.edu;
    # }

    # location /api/ {
    #     proxy_pass  http://backend/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}
